version: '3'
services:
  service1:
    build: ./service1
    ports:
      - "5001:5001"
    env_file:
      - ./service1/.env
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      # - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=claspMobileDB
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - mongo

  service2:
    build: ./service2
    ports:
      - "5002:5002"
    env_file:
      - ./service2/.env
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      # - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=adaptiveTextDB
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - mongo

    # mongo:
    #   image: mongo
    #   restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    # volumes:
    #   - mongo_data:/data/db
    # ports:
    #   - "27017:27017"

    # nginx:
    #   image: nginx
    #   volumes:
    #     - ./nginx.conf:/etc/nginx/nginx.conf
    #   ports:
    #     - "80:80"
    #   depends_on:
    #     - service1
    #     - service2

    # volumes:
    #   mongo_data:
