# version: '3'
# services:
#   flaskapp:
#     build: .
#     container_name: flaskapp
#     env_file:
#       - .env
#     expose:
#       - "8000"
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - flaskapp

version: '3'
services:
  adaptive-text:
    build: ./adaptive-text
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/adaptiveTextDB
    depends_on:
      - mongo

  clasp-mobile:
    build: ./clasp-mobile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/claspMobileDB
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
